#file Makefile
#author Klaus Krapfenbauer MatrNr.:0926457
#brief Makefile for EProg TM serie01
#date 07.10.2012


CFLAGS=-g -ansi -pedantic -Wall
CC=gcc


kreis: kreis.c
	$(CC) $(FLAGS) -o kreis kreis.c

sortMe: sortMe.c
	$(CC) $(FLAGS) -o sortMe sortMe.c


clean:
	rm -f *.o kreis

.PHONY: clean all doc
